// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/abrarnaim015/belajar-golang-dependency-injection/controller"
	"github.com/abrarnaim015/belajar-golang-dependency-injection/middleware"
	"github.com/abrarnaim015/belajar-golang-dependency-injection/repository"
	"github.com/abrarnaim015/belajar-golang-dependency-injection/service"
	"github.com/go-playground/validator"
	"github.com/google/wire"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepository := repository.NewCategoryRepositoryImpl()
	db := NewDB()
	validate := validator.New()
	categoryService := service.NewCategoryServiceImpl(categoryRepository, db, validate)
	categoryController := controller.NewCategoryControllerImpl(categoryService)
	router := NewRouter(categoryController)
	authMiddleware := middleware.NewAuthMiddlewareImpl(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepositoryImpl, service.NewCategoryServiceImpl, controller.NewCategoryControllerImpl)
